//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NO2A_H08_SuFaturasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int ID { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public Nullable<byte> Yetki { get; set; }
    }
}
