//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NO2A_H08_SuFaturasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MusteriList
    {
        public int ID { get; set; }
        public string TCKN { get; set; }
        public string AdSoyad { get; set; }
        public string SayacNo { get; set; }
        public string CepTelefonu { get; set; }
        public string Adres { get; set; }
        public int Il_ID { get; set; }
        public int Ilce_ID { get; set; }
        public string Il_Adi { get; set; }
        public string IlceAdi { get; set; }
    }
}
